stages:
  - docker

docker_build_master:
  stage: docker
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - export VERSION=$CI_PIPELINE_ID
  script:
    - echo "$CI_REGISTRY_IMAGE"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --build-arg pip_index=$PIP_INDEX
      --build-arg pip_index_url=$PIP_INDEX_URL
      --build-arg version=$VERSION
      --destination $CI_REGISTRY_IMAGE:$VERSION
      --destination $CI_REGISTRY_IMAGE:latest
